In [7]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [17]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df.shape

(5572, 3)

In [15]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [20]:
X_train.shape

(4457,)

In [23]:
X_test.shape

(1115,)

In [25]:
type(X_train)

pandas.core.series.Series

In [27]:
X_train[:4]

1315    Got but got 2 colours lor. One colour is quite...
3026    What part of "don't initiate" don't you unders...
40      Pls go ahead with watts. I just wanted to be s...
1269    Can U get 2 phone NOW? I wanna chat 2 set up m...
Name: Message, dtype: object

In [29]:
y_train[:4]

1315    0
3026    0
40      0
1269    1
Name: spam, dtype: int64

In [31]:
X_train.values

array(["Got but got 2 colours lor. One colour is quite light n e other is darker lor. Actually i'm done she's styling my hair now.",
       'What part of "don\'t initiate" don\'t you understand',
       'Pls go ahead with watts. I just wanted to be sure. Do have a great weekend. Abiola',
       ...,
       "That's good. Lets thank God. Please complete the drug. Have lots of water. And have a beautiful day.",
       'I know you are serving. I mean what are you doing now.',
       'Did u got that persons story'], dtype=object)

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7690 sparse matrix of type '<class 'numpy.int64'>'
	with 59055 stored elements in Compressed Sparse Row format>

In [41]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
X_train_cv.shape

(4457, 7690)

In [43]:
v.vocabulary_

{'got': 3193,
 'but': 1565,
 'colours': 1880,
 'lor': 4177,
 'one': 4889,
 'colour': 1878,
 'is': 3730,
 'quite': 5467,
 'light': 4083,
 'other': 4947,
 'darker': 2148,
 'actually': 805,
 'done': 2392,
 'she': 6017,
 'styling': 6501,
 'my': 4627,
 'hair': 3292,
 'now': 4796,
 'what': 7420,
 'part': 5037,
 'of': 4844,
 'don': 2391,
 'initiate': 3668,
 'you': 7651,
 'understand': 7094,
 'pls': 5196,
 'go': 3154,
 'ahead': 872,
 'with': 7494,
 'watts': 7356,
 'just': 3859,
 'wanted': 7325,
 'to': 6885,
 'be': 1263,
 'sure': 6575,
 'do': 2360,
 'have': 3348,
 'great': 3230,
 'weekend': 7388,
 'abiola': 753,
 'can': 1619,
 'get': 3110,
 'phone': 5134,
 'wanna': 7322,
 'chat': 1725,
 'set': 5972,
 'up': 7129,
 'meet': 4392,
 'call': 1596,
 'me': 4375,
 'on': 4884,
 '09096102316': 243,
 'cum': 2096,
 'here': 3406,
 '2moro': 399,
 'luv': 4237,
 'jane': 3775,
 'xx': 7601,
 'calls': 1610,
 'minmoremobsemspobox45po139wa': 4459,
 'ur': 7147,
 'paper': 5019,
 'in': 3628,
 'morn': 4547,
 'or': 4923,

In [57]:
v.get_feature_names_out()[805]

'actually'

In [53]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [55]:
np.where(X_train_np[0] != 0)

(array([ 805, 1565, 1878, 1880, 2148, 2392, 3193, 3292, 3730, 4083, 4177,
        4627, 4796, 4889, 4947, 5467, 6017, 6501], dtype=int64),)

In [59]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [61]:
X_test_cv = v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

classification_report(y_test, y_)